# Generated by Django 4.1.1 on 2022-09-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker_app', '0002_habit_dailyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
