# Generated by Django 4.1.1 on 2022-09-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker_app', '0003_alter_dailyrecord_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='amount',
            new_name='daily_amount',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='past_action',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='unit',
        ),
    ]
